### PR TITLE
Update Readme, Resolve Relative Pathing

### PR DESCRIPTION
**Pull request by larryzhang95**

### CODE REVIEW

**Comment by abhilasha-kumar** [comment]
Don't we also need to update the paths to our lexical data/global path variables? I am getting errors like "cannot find X" if I try to run forager from outside the forager directory. E.g., I tried to run `python forager/run_foraging.py --data forager/data/fluency_lists/psyrev_data.txt --pipeline evaluate_data` and got the error `No such file or directory: 'data/lexical_data/USE_frequencies.csv'`.

**Comment by larryzhang95** [comment]
That might be more difficult to figure out in terms of pathing for those files, since they're within the forager directory. Let me try and see if I can address it tomorrow.

**Comment by larryzhang95** [comment]
Given your specific example, I found a way to resolve relative pathing w.r.t. the lexical data paths included in our pipeline.

**Review by abhilasha-kumar — APPROVED** [review]
looks good!

**Pull request merged**
